### ISSUE TITLE
curl 7.87.0: core dump in destructor

### ISSUE THREAD

**Issue by 0-wiz-0** [Sude-/lgogdownloader#232]
After updating from curl 7.86.0 to curl 7.87.0, lgogdownloader started dumping core when cleaning up before exiting.
The easiest use case is:
```
lgogdownloader --download --game $ANY_GAME
```
The downloads are fine, but then I get a core dump:
```
(gdb) bt
#0  0x0000708defb2db10 in ?? ()
#1  0x0000708de55f9c43 in bio_read_intern (b=0x708defb5b580, data=data@entry=0x708def681a83, dlen=dlen@entry=5, readbytes=readbytes@entry=0x7f7fffe22a28) at /usr/src/crypto/external/bsd/openssl/dist/crypto/bio/bio_lib.c:270
#2  0x0000708de55fa161 in BIO_read (b=<optimized out>, data=data@entry=0x708def681a83, dlen=dlen@entry=5) at /usr/src/crypto/external/bsd/openssl/dist/crypto/bio/bio_lib.c:296
#3  0x0000708de5a25b21 in ssl3_read_n (s=s@entry=0x708defac3800, n=n@entry=5, max=5, extend=extend@entry=0, clearold=clearold@entry=1, readbytes=readbytes@entry=0x7f7fffe22af8) at /usr/src/crypto/external/bsd/openssl/dist/ssl/record/rec_layer_s3.c:296
#4  0x0000708de5a22c65 in ssl3_get_record (s=s@entry=0x708defac3800) at /usr/src/crypto/external/bsd/openssl/dist/ssl/record/ssl3_record.c:207
#5  0x0000708de5a2740a in ssl3_read_bytes (s=<optimized out>, type=23, recvd_type=0x0, buf=0x7f7fffe22ce0 " -\342\377\177\177", len=32, peek=0, readbytes=0x7f7fffe22cc8) at /usr/src/crypto/external/bsd/openssl/dist/ssl/record/rec_layer_s3.c:1301
#6  0x0000708de5a615c9 in ssl3_read_internal (s=0x708defac3800, buf=0x7f7fffe22ce0, len=32, peek=0, readbytes=0x7f7fffe22cc8) at /usr/src/crypto/external/bsd/openssl/dist/ssl/s3_lib.c:4465
#7  0x0000708de5a57e7d in SSL_read (s=<optimized out>, buf=buf@entry=0x7f7fffe22ce0, num=num@entry=32) at /usr/src/crypto/external/bsd/openssl/dist/ssl/ssl_lib.c:1785
#8  0x0000708dee08016c in ossl_close (cf=<optimized out>, data=<optimized out>) at vtls/openssl.c:1950
#9  0x0000708dee085bbc in cf_close (data=0x708defaf4000, cf=0x708defba52b0) at vtls/vtls.c:1439
#10 ssl_cf_close (cf=0x708defba52b0, data=0x708defaf4000) at vtls/vtls.c:1488
#11 0x0000708dee074611 in conn_shutdown (data=0x708defaf4000) at url.c:749
#12 Curl_disconnect (data=0x708defaf4000, conn=0x708defb5d500, dead_connection=false) at url.c:861
#13 0x0000708dee01fc78 in Curl_conncache_close_all_connections (connc=connc@entry=0x708defb840b0) at conncache.c:544
#14 0x0000708dee054d64 in curl_multi_cleanup (multi=0x708defb83fc0) at multi.c:2763
#15 0x0000708dee0748e9 in Curl_close (datap=datap@entry=0x7f7fffe232f8) at url.c:394
#16 0x0000708dee02be2d in curl_easy_cleanup (data=<optimized out>) at easy.c:798
#17 0x0000000000453323 in galaxyAPI::~galaxyAPI() ()
#18 0x0000000000453352 in galaxyAPI::~galaxyAPI() ()
#19 0x00000000004216e6 in Downloader::~Downloader() ()
#20 0x0000000000419186 in main ()
```

I initially reported this as a ![curl bug](https://github.com/curl/curl/issues/10150) since it started happening with the upgrade, but the curl developers think it's a bug in lgogdownloader, to quote:
> I think I nailed it down. The lgogdownloader code calls curl_global_cleanup() before it closes the easy handle. This will free SSL structures that are then used afterwards in closing the connection.
> curl_global_cleanup() is supposed to be the last call to cURL in an application.

I tried fixing this by manually calling the destructor for the download object like this:
```
diff --git a/main.cpp b/main.cpp
index 8d27135..ecfaaa1 100644
--- a/main.cpp
+++ b/main.cpp
@@ -881,6 +881,9 @@ int main(int argc, char *argv[])
     if (!Globals::globalConfig.sOrphanRegex.empty() && Globals::globalConfig.bDownload)
         downloader.checkOrphans();
 
+    // Call destructor manually because it must happen before curl_global_cleanup()
+    downloader.~Downloader();
+
     curl_global_cleanup();
 
     return res;
```
but this just causes a core dump in the destructor:
```
(gdb) bt
#0  0x0000000000421708 in Downloader::~Downloader() ()
#1  0x0000000000419195 in main ()
```
so I'd like you to take a look at this, please.

For reproducing the core dump, I think it should be enough to compile against curl 7.87.0.

**Comment by Sude-** [comment]
6ce6aeb should fix this

**Comment by 0-wiz-0** [comment]
Fixed indeed, thank you!
