### ISSUE TITLE
crashes on ubuntu 14.04

### ISSUE THREAD

**Issue by Mitmischer** [Sude-/lgogdownloader#70]
Hello,

I installed lgogdownloader from the webupd8-ppa (ppa:nilarimogard/webupd8 ).

My system is ubuntu 14.04.3.

Upon starting lgogdownloader the first time, I get:
```
Email: ...
Password: 
API: Login successful
Saving config: /home/max/.config/lgogdownloader/config.cfg
fish: Job 1, 'lgogdownloader' durch Signal SIGSEGV (Adressbereichsfehler) beendet
```
where the last line indicates a SIGSEGV. Running it a second time gives:
```
Email: max.beikirch@unitybox.de
Password: 
API: Login successful
*** Error in `lgogdownloader': double free or corruption (fasttop): 0x00000000007a5170 ***
fish: Job 1, 'lgogdownloader' durch Signal SIGABRT (Abbruch) beendet
```

Running it repeatedly will always give me the last error message.
Note that the program creates the file `/home/max/.config/lgogdownloader/config.cfg`. If `/home/max/.config/lgogdownloader/` is deleted, a program run will again give the first error message.

backtracks from gdb:
first run (no .config/lgogdownloader):
```
#0  __memcpy_sse2_unaligned () at ../sysdeps/x86_64/multiarch/memcpy-sse2-unaligned.S:36
#1  0x00007ffff63133c0 in std::string::_Rep::_M_clone(std::allocator<char> const&, unsigned long) () from /usr/local/lib/libstdc++.so.6
#2  0x00007ffff6313b7c in std::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(std::string const&) () from /usr/local/lib/libstdc++.so.6
#3  0x00000000004182ac in ?? ()
#4  0x00007ffff598fec5 in __libc_start_main (main=0x413e20, argc=1, argv=0x7fffffffe408, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffffffe3f8)
    at libc-start.c:287
#5  0x0000000000413ad9 in ?? ()
```
subsequent runs:
```
#0  0x00007ffff59a4cc9 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#1  0x00007ffff59a80d8 in __GI_abort () at abort.c:89
#2  0x00007ffff59e1394 in __libc_message (do_abort=do_abort@entry=1, fmt=fmt@entry=0x7ffff5aefb28 "*** Error in `%s': %s: 0x%s ***\n") at ../sysdeps/posix/libc_fatal.c:175
#3  0x00007ffff59ed66e in malloc_printerr (ptr=<optimized out>, str=0x7ffff5aefcf0 "double free or corruption (fasttop)", action=1) at malloc.c:4996
#4  _int_free (av=<optimized out>, p=<optimized out>, have_lock=0) at malloc.c:3840
#5  0x00007ffff6313c5f in std::string::assign(std::string const&) () from /usr/local/lib/libstdc++.so.6
#6  0x000000000042a80c in ?? ()
#7  0x00007ffff6bef1cb in boost::program_options::variables_map::notify() () from /usr/lib/x86_64-linux-gnu/libboost_program_options.so.1.54.0
#8  0x00000000004181d7 in ?? ()
#9  0x00007ffff598fec5 in __libc_start_main (main=0x413e20, argc=1, argv=0x7fffffffe408, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffffffe3f8)
    at libc-start.c:287
#10 0x0000000000413ad9 in ?? ()
```

Interestingly, the program ends without errors, if the provided credentials are wrong.

those are my boost libraries:
```
ii  libboost-date-time1.54.0:amd64                        1.54.0-4ubuntu3.1                     amd64        set of date-time libraries based on generic programming concepts
ii  libboost-filesystem1.54.0:amd64                       1.54.0-4ubuntu3.1                     amd64        filesystem operations (portable paths, iteration over directories, etc) in C++
rc  libboost-iostreams1.49.0                              1.49.0-4                              amd64        Boost.Iostreams Library
rc  libboost-iostreams1.53.0:amd64                        1.53.0-6+exp3ubuntu8                  amd64        Boost.Iostreams Library
ii  libboost-iostreams1.54.0:amd64                        1.54.0-4ubuntu3.1                     amd64        Boost.Iostreams Library
ii  libboost-locale1.54.0:amd64                           1.54.0-4ubuntu3.1                     amd64        C++ facilities for localization
ii  libboost-program-options1.54.0:amd64                  1.54.0-4ubuntu3.1                     amd64        program options library for C++
ii  libboost-regex1.54.0:amd64                            1.54.0-4ubuntu3.1                     amd64        regular expression library for C++
ii  libboost-system1.54.0:amd64                           1.54.0-4ubuntu3.1                     amd64        Operating system (e.g. diagnostics support) library
ii  libboost-thread1.54.0:amd64                           1.54.0-4ubuntu3.1                     amd64        portable C++ multi-threading
```

my libc is version 2.19 and my libstdc++ is 4.8.4.

Will this do? I could also build a debug lgogdownloader and post its gdb here, if necessary.

**Comment by a-detiste** [comment]
Please file this bug against PPA owner !

Or just compile from source & smash /usr/bin/lgogdownloader with generated binary.

---

Maybe you'd like my PPA ? But then I didn't yet cared about a lgogdownloader for 14.04

https://launchpad.net/~alexandre-detiste/+archive/ubuntu/ppa/+packages

**Comment by Sude-** [comment]
Does 8780b9c fix this?

**Comment by Mitmischer** [comment]
@a-detiste Thank you - I tried your ppa, but the error persisted.
@Sude- Yes, this commit actually fixed the problem! Thank you very much.
For reference: I also tried compiling against 97d01b2 which is the last version before the fix. In this version, the error was still there - as such, I think, we fixed a real bug here.

**Comment by a-detiste** [comment]
sorry for complaining,

I don't know if anybody uses this PPA, but I fixed it anyway:

https://launchpadlibrarian.net/227007006/lgogdownloader_2.26-1~gdp%2Btrusty_2.26-2~gdp%2Btrusty.diff.gz
